name: CustomAdvancements
version: ${project.version}
main: me.tippie.customadvancements.CustomAdvancements
api-version: 1.16
website: https://tippie.me
commands:
  customadvancements:
    aliases: [ ca , advancements]
    description: CustomAdvancements base command
permissions:
  customadvancements.command.help:
    default: true
